development:
  adapter: postgresql
  encoding: unicode
  database: timetracker_recording_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: timetracker_recording_test
  pool: 5
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: timetracker_production
  pool: 5
