development:
  adapter: postgresql
  encoding: unicode
  database: timetracker_recording_development
  pool: 5
  username: saas-cms
  passowrd: password1
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: timetracker_recording_test
  pool: 5
  username: saas-cms
  passowrd: password1
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: timetracker_production
  username: saas-cms
  passowrd: password1
  pool: 5
